language: rust
rust:
  - 1.9.0

addons:
  apt:
    packages:
      - kcov

after_success: |
  kcov --version &&
  for file in target/debug/lion-*; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

